"use client";

import Link from "next/link";
import {useState} from "react";
import {Brand} from "@/components/shared/brand";
import {authApi} from "@/features/auth/api/auth.api";
import {apiError} from "@/lib/axios/interceptors";

export default function Page(){
  const[email,setEmail]=useState(""),[otp,setOtp]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[sent,setSent]=useState(false),[done,setDone]=useState(false),[pending,setPending]=useState(false),[error,setError]=useState<unknown>();
  const passwordValid=password.length>=12&&/[A-Z]/.test(password)&&/[a-z]/.test(password)&&/[0-9]/.test(password);
  const request=async()=>{setPending(true);setError(undefined);try{await authApi.requestPasswordReset(email);setSent(true)}catch(requestError){setError(requestError)}finally{setPending(false)}};
  const reset=async()=>{setPending(true);setError(undefined);try{await authApi.confirmPasswordReset({email,otp,password});setDone(true)}catch(requestError){setError(requestError)}finally{setPending(false)}};
  return <div className="auth-box login-page"><Brand/><h1>Quên mật khẩu</h1><p className="subtitle">Nhập email để nhận mã OTP đặt lại mật khẩu. Mã dùng một lần và hết hạn sau 10 phút.</p>{done?<><p className="success">Mật khẩu đã được đặt lại. Tất cả phiên đăng nhập cũ đã bị thu hồi.</p><p className="helper"><Link href="/login">Đăng nhập bằng mật khẩu mới</Link></p></>:<>{!sent?<><label className="field"><span>Địa chỉ email</span><input className="input" type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="ban@congty.com"/></label><button className="btn block" disabled={!/^\S+@\S+\.\S+$/.test(email)||pending} onClick={request}>{pending?"Đang gửi…":"Gửi mã OTP"}</button></>:<><p className="success">Nếu email tồn tại, mã OTP đã được gửi đến hộp thư của bạn.</p><label className="field"><span>Mã OTP gồm 6 chữ số</span><input className="input" inputMode="numeric" maxLength={6} value={otp} onChange={event=>setOtp(event.target.value.replace(/\D/g,""))} placeholder="000000"/></label><label className="field"><span>Mật khẩu mới</span><input className="input" type="password" value={password} onChange={event=>setPassword(event.target.value)} placeholder="Tối thiểu 12 ký tự, có hoa, thường và số"/></label><label className="field"><span>Xác nhận mật khẩu mới</span><input className="input" type="password" value={confirm} onChange={event=>setConfirm(event.target.value)}/></label>{confirm&&password!==confirm&&<p className="error">Mật khẩu xác nhận không khớp.</p>}<button className="btn block" disabled={otp.length!==6||!passwordValid||password!==confirm||pending} onClick={reset}>{pending?"Đang đặt lại…":"Đặt lại mật khẩu"}</button><p className="helper"><button className="link-button" disabled={pending} onClick={request}>Gửi lại mã OTP</button></p></>}{error!==undefined&&<p className="error">{apiError(error).message}</p>}<p className="helper"><Link href="/login">← Quay lại đăng nhập</Link></p></>}</div>;
}
