"use client";

import Link from "next/link";
import {useState} from "react";
import {Brand} from "@/components/shared/brand";
import {authApi} from "@/features/auth/api/auth.api";
import {apiError} from "@/lib/axios/interceptors";

export default function Page(){
  const[displayName,setDisplayName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[pending,setPending]=useState(false),[done,setDone]=useState(false),[error,setError]=useState<unknown>(),[validationError,setValidationError]=useState("");
  const passwordValid=password.length>=12&&/[A-Z]/.test(password)&&/[a-z]/.test(password)&&/[0-9]/.test(password);
  const submit=async()=>{setValidationError("");if(!/^\S+@\S+\.\S+$/.test(email)){setValidationError("Vui lòng nhập địa chỉ email hợp lệ.");return}if(displayName&&displayName.trim().length<2){setValidationError("Tên hiển thị phải có ít nhất 2 ký tự.");return}if(!passwordValid){setValidationError("Mật khẩu phải có ít nhất 12 ký tự, gồm chữ hoa, chữ thường và chữ số.");return}if(password!==confirm){setValidationError("Mật khẩu xác nhận không khớp.");return}setPending(true);setError(undefined);try{await authApi.register({email,password,displayName:displayName||undefined});setDone(true)}catch(requestError){setError(requestError)}finally{setPending(false)}};
  return <div className="auth-box login-page"><Brand/><h1>Tạo tài khoản</h1><p className="subtitle">Đăng ký bằng email và xác minh tài khoản qua liên kết bảo mật.</p>{done?<><div className="success"><strong>Kiểm tra hộp thư của bạn</strong><br/>Liên kết xác minh đã được gửi đến {email} và sẽ hết hạn sau 20 phút. Liên kết chỉ sử dụng được một lần.</div><p className="helper"><Link href="/login">Quay lại đăng nhập</Link></p></>:<><label className="field"><span>Tên hiển thị</span><input className="input" value={displayName} onChange={event=>setDisplayName(event.target.value)} placeholder="Nguyễn Văn A"/></label><label className="field"><span>Địa chỉ email</span><input className="input" type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="ban@congty.com"/></label><label className="field"><span>Mật khẩu</span><input className="input" type="password" value={password} onChange={event=>setPassword(event.target.value)} placeholder="Tối thiểu 12 ký tự, có hoa, thường và số"/><small className={password&&passwordValid?"success":"notice"}>Ít nhất 12 ký tự, gồm chữ hoa, chữ thường và chữ số.</small></label><label className="field"><span>Xác nhận mật khẩu</span><input className="input" type="password" value={confirm} onChange={event=>setConfirm(event.target.value)}/></label>{confirm&&password!==confirm&&<p className="error">Mật khẩu xác nhận không khớp.</p>}{validationError&&<p className="error">{validationError}</p>}{error!==undefined&&<p className="error">{apiError(error).message}</p>}<button className="btn block" disabled={pending} onClick={submit}>{pending?"Đang đăng ký…":"Đăng ký"}</button><p className="helper">Đã có tài khoản? <Link href="/login">Đăng nhập</Link></p></>}</div>;
}
