"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { changePassword, getCurrentUser, getSessions, revokeSession, type AuthSession } from "../api/auth.api";
import { EmailVerificationNotice } from "./email-verification-notice";
import { useAuth } from "./auth-provider";
import { LogoutButton } from "./logout-button";
export function AccountPanel() {
 const {user,isLoading,setAuthenticatedUser}=useAuth(); const [sessions,setSessions]=useState<AuthSession[]>([]); const [message,setMessage]=useState("");
 useEffect(()=>{if(user) void getSessions().then(setSessions)},[user]);
 if(isLoading)return <p>Dang khoi phuc phien...</p>; if(!user)return <p>Bạn chưa đăng nhập. <Link href="/login">Đăng nhập</Link></p>;
 const hasPassword=user.hasPassword;
 async function submitPassword(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);try{await changePassword(String(d.get("newPassword")),hasPassword?String(d.get("currentPassword")):undefined);setAuthenticatedUser(await getCurrentUser());e.currentTarget.reset();setMessage(hasPassword?"Đã đổi mật khẩu.":"Đã đặt mật khẩu. Bạn có thể đăng nhập bằng email và mật khẩu.")}catch{setMessage(hasPassword?"Mật khẩu hiện tại không đúng hoặc mật khẩu mới chưa hợp lệ.":"Không thể đặt mật khẩu mới.")}}
 return <section className="w-full max-w-5xl"><EmailVerificationNotice/><div className="border border-[var(--ink)] bg-[var(--paper)] p-6"><p className="font-mono text-xs">ACCOUNT</p><h1 className="mt-2 text-5xl">{user.displayName??"Tai khoan"}</h1><p className="mt-4">{user.email}</p><div className="mt-6 flex gap-4">{user.permissions.includes("users:read")&&<Link className="underline" href="/admin/users">Quan tri</Link>}<LogoutButton/></div></div><div className="mt-6 grid gap-6 lg:grid-cols-[0.8fr_1.2fr]"><nav className="border bg-[var(--paper)] p-6"><p className="font-mono text-xs">BAO MAT</p><h2 className="mt-2 text-3xl">Tài khoản</h2><div className="mt-5 space-y-3 text-sm"><a className="block" href="#password">Đổi mật khẩu</a><a className="block" href="#two-factor">Xác thực 2 bước</a><a className="block" href="#sessions">Phiên đăng nhập</a><a className="block" href="#devices">Thiết bị đã đăng nhập</a></div></nav><div className="space-y-6"><form id="password" onSubmit={submitPassword} className="border bg-[var(--paper)] p-6"><h2 className="text-2xl">{hasPassword ? "Đổi mật khẩu" : "Đặt mật khẩu"}</h2><div className="mt-4 grid gap-3">{hasPassword && <input className="border p-3" name="currentPassword" type="password" placeholder="Mật khẩu hiện tại" required/>}<input className="border p-3" name="newPassword" type="password" minLength={12} placeholder="Mật khẩu mới" required/><button className="w-fit border px-4 py-2" type="submit">{hasPassword ? "Cập nhật mật khẩu" : "Đặt mật khẩu"}</button>{message&&<p role="status">{message}</p>}</div></form><div id="two-factor" className="border bg-[var(--paper)] p-6"><h2 className="text-2xl">Xác thực 2 bước</h2><p className="mt-2 text-sm">Tính năng đang được chuẩn bị.</p></div><div id="sessions" className="border bg-[var(--paper)] p-6"><h2 className="text-2xl">Phiên đăng nhập</h2><ul className="mt-4 space-y-3">{sessions.map(s=><li className="flex justify-between border-t pt-3" key={s.id}><span>{new Date(s.createdAt).toLocaleString("vi-VN")}{s.current?" · Thiết bị này":""}</span>{!s.current&&<button className="underline" type="button" onClick={()=>void revokeSession(s.id).then(()=>setSessions(x=>x.filter(i=>i.id!==s.id)))}>Thu hồi</button>}</li>)}</ul></div><div id="devices" className="border bg-[var(--paper)] p-6"><h2 className="text-2xl">Thiết bị đã đăng nhập</h2><p className="mt-2 text-sm">Danh sách thiết bị được đồng bộ từ các phiên hoạt động.</p></div></div></div></section>;
}
